#!/bin/bash

sudo nmap --script=/home/neo/sc/ -sV -n -v --defeat-rst-ratelimit --host-timeout 600s --stats-every 10s -oA report -d 192.168.0.0/24
xsltproc -o report.html nmap-bootstrap.xsl report.xml
